version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "4200:4200"

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "3000:3000"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: parcels
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: parcelsdb
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8060:8080"
