FROM node:20.10.0

WORKDIR /app

RUN npm install -g @angular/cli

COPY ../frontend/package.json ./
COPY ../frontend/package-lock.json ./

RUN npm install

COPY ../frontend .

RUN ng build

EXPOSE 4200

CMD ng serve --host 0.0.0.0
